#
# Copyright 2013 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
LOCAL_PATH := vendor/zte/geek

PRODUCT_COPY_FILES += \
 $(LOCAL_PATH)/proprietary/system/bin/bd_prov:system/bin/bd_prov \
 $(LOCAL_PATH)/proprietary/system/bin/fg_conf:system/bin/fg_conf \
 $(LOCAL_PATH)/proprietary/system/bin/load_bcmdriver:system/bin/load_bcmdriver \
 $(LOCAL_PATH)/proprietary/system/bin/mmgr:system/bin/mmgr \
 $(LOCAL_PATH)/proprietary/system/bin/rild:system/bin/rild \
 $(LOCAL_PATH)/proprietary/system/bin/wlan_prov:system/bin/wlan_prov \
 $(LOCAL_PATH)/proprietary/system/etc/asound.conf:system/etc/asound.conf \
 $(LOCAL_PATH)/proprietary/system/etc/asound-vv.conf:system/etc/asound-vv.conf \
 $(LOCAL_PATH)/proprietary/system/etc/audio_effects.conf:system/etc/audio_effects.conf \
 $(LOCAL_PATH)/proprietary/system/etc/audio_policy.conf:system/etc/audio_policy.conf \
 $(LOCAL_PATH)/proprietary/system/etc/camera_profiles.xml:system/etc/camera_profiles.xml \
 $(LOCAL_PATH)/proprietary/system/etc/fg_config.bin:system/etc/fg_config.bin \
 $(LOCAL_PATH)/proprietary/system/etc/gps.conf:system/etc/gps.conf \
 $(LOCAL_PATH)/proprietary/system/etc/media_codecs.xml:system/etc/media_codecs.xml \
 $(LOCAL_PATH)/proprietary/system/etc/media_profiles.xml:system/etc/media_profiles.xml \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_bt_carkit_csv_nb.bin:system/etc/phonecall_es305b_bt_carkit_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_bt_carkit_csv_wb.bin:system/etc/phonecall_es305b_bt_carkit_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_bt_carkit_voip_nb.bin:system/etc/phonecall_es305b_bt_carkit_voip_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_bt_carkit_voip_wb.bin:system/etc/phonecall_es305b_bt_carkit_voip_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_bt_hsp_csv_nb.bin:system/etc/phonecall_es305b_bt_hsp_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_bt_hsp_csv_wb.bin:system/etc/phonecall_es305b_bt_hsp_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_bt_hsp_voip_nb.bin:system/etc/phonecall_es305b_bt_hsp_voip_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_bt_hsp_voip_wb.bin:system/etc/phonecall_es305b_bt_hsp_voip_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_csv_nb.bin:system/etc/phonecall_es305b_close_talk_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_csv_wb.bin:system/etc/phonecall_es305b_close_talk_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_hac_csv_nb.bin:system/etc/phonecall_es305b_close_talk_hac_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_hac_csv_wb.bin:system/etc/phonecall_es305b_close_talk_hac_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_hac_voip_nb.bin:system/etc/phonecall_es305b_close_talk_hac_voip_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_hac_voip_wb.bin:system/etc/phonecall_es305b_close_talk_hac_voip_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_tty_hco_csv_nb.bin:system/etc/phonecall_es305b_close_talk_tty_hco_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_tty_hco_csv_wb.bin:system/etc/phonecall_es305b_close_talk_tty_hco_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_tty_hco_hac_csv_nb.bin:system/etc/phonecall_es305b_close_talk_tty_hco_hac_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_tty_hco_hac_csv_wb.bin:system/etc/phonecall_es305b_close_talk_tty_hco_hac_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_tty_vco_csv_nb.bin:system/etc/phonecall_es305b_close_talk_tty_vco_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_tty_vco_csv_wb.bin:system/etc/phonecall_es305b_close_talk_tty_vco_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_voip_nb.bin:system/etc/phonecall_es305b_close_talk_voip_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_close_talk_voip_wb.bin:system/etc/phonecall_es305b_close_talk_voip_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_headphone_close_talk_csv_nb.bin:system/etc/phonecall_es305b_headphone_close_talk_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_headphone_close_talk_csv_wb.bin:system/etc/phonecall_es305b_headphone_close_talk_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_headphone_close_talk_voip_nb.bin:system/etc/phonecall_es305b_headphone_close_talk_voip_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_headphone_close_talk_voip_wb.bin:system/etc/phonecall_es305b_headphone_close_talk_voip_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_headset_close_talk_csv_nb.bin:system/etc/phonecall_es305b_headset_close_talk_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_headset_close_talk_csv_wb.bin:system/etc/phonecall_es305b_headset_close_talk_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_headset_close_talk_voip_nb.bin:system/etc/phonecall_es305b_headset_close_talk_voip_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_headset_close_talk_voip_wb.bin:system/etc/phonecall_es305b_headset_close_talk_voip_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_headset_tty_full_csv_nb.bin:system/etc/phonecall_es305b_headset_tty_full_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_headset_tty_full_csv_wb.bin:system/etc/phonecall_es305b_headset_tty_full_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_no_acoustic_csv_nb.bin:system/etc/phonecall_es305b_no_acoustic_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_no_acoustic_csv_wb.bin:system/etc/phonecall_es305b_no_acoustic_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_no_acoustic_voip_nb.bin:system/etc/phonecall_es305b_no_acoustic_voip_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_no_acoustic_voip_wb.bin:system/etc/phonecall_es305b_no_acoustic_voip_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_speaker_far_talk_csv_nb.bin:system/etc/phonecall_es305b_speaker_far_talk_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_speaker_far_talk_csv_wb.bin:system/etc/phonecall_es305b_speaker_far_talk_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_speaker_far_talk_tty_hco_csv_nb.bin:system/etc/phonecall_es305b_speaker_far_talk_tty_hco_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_speaker_far_talk_tty_hco_csv_wb.bin:system/etc/phonecall_es305b_speaker_far_talk_tty_hco_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_speaker_far_talk_tty_vco_csv_nb.bin:system/etc/phonecall_es305b_speaker_far_talk_tty_vco_csv_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_speaker_far_talk_tty_vco_csv_wb.bin:system/etc/phonecall_es305b_speaker_far_talk_tty_vco_csv_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_speaker_far_talk_voip_nb.bin:system/etc/phonecall_es305b_speaker_far_talk_voip_nb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/phonecall_es305b_speaker_far_talk_voip_wb.bin:system/etc/phonecall_es305b_speaker_far_talk_voip_wb.bin \
 $(LOCAL_PATH)/proprietary/system/etc/thermal_sensor_config.xml:system/etc/thermal_sensor_config.xml \
 $(LOCAL_PATH)/proprietary/system/etc/thermal_throttle_config.xml:system/etc/thermal_throttle_config.xml \
 $(LOCAL_PATH)/proprietary/system/etc/wrs_omxil_components.list:system/etc/wrs_omxil_components.list \
 $(LOCAL_PATH)/proprietary/system/etc/bluetooth/bt_vendor.conf:system/etc/bluetooth/bt_vendor.conf \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/ParameterFrameworkConfigurationVibrator.xml:system/etc/parameter-framework/ParameterFrameworkConfigurationVibrator.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/ParameterFrameworkConfiguration.xml:system/etc/parameter-framework/ParameterFrameworkConfiguration.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Settings/Audio/AudioConfigurableDomains.xml:system/etc/parameter-framework/Settings/Audio/AudioConfigurableDomains.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Settings/Vibrator/VibratorConfigurableDomains.xml:system/etc/parameter-framework/Settings/Vibrator/VibratorConfigurableDomains.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Audio/AudienceSubsystem.xml:system/etc/parameter-framework/Structure/Audio/AudienceSubsystem.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Audio/AudioClass.xml:system/etc/parameter-framework/Structure/Audio/AudioClass.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Audio/BluetoothSubsystem.xml:system/etc/parameter-framework/Structure/Audio/BluetoothSubsystem.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Audio/CirrusLogicSubsystem.xml:system/etc/parameter-framework/Structure/Audio/CirrusLogicSubsystem.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Audio/ConfigurationSubsystem.xml:system/etc/parameter-framework/Structure/Audio/ConfigurationSubsystem.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Audio/IMCSubsystem.xml:system/etc/parameter-framework/Structure/Audio/IMCSubsystem.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Audio/IntelSSPSubsystem.xml:system/etc/parameter-framework/Structure/Audio/IntelSSPSubsystem.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Audio/LPEMixerSubsystem.xml:system/etc/parameter-framework/Structure/Audio/LPEMixerSubsystem.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Audio/LPESubsystem.xml:system/etc/parameter-framework/Structure/Audio/LPESubsystem.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Audio/SysfsPmdownTimeSubsystem.xml:system/etc/parameter-framework/Structure/Audio/SysfsPmdownTimeSubsystem.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Vibrator/SysfsVibratorClass.xml:system/etc/parameter-framework/Structure/Vibrator/SysfsVibratorClass.xml \
 $(LOCAL_PATH)/proprietary/system/etc/parameter-framework/Structure/Vibrator/SysfsVibratorSubsystem.xml:system/etc/parameter-framework/Structure/Vibrator/SysfsVibratorSubsystem.xml \
 $(LOCAL_PATH)/proprietary/system/etc/wifi/hostapd.conf:system/etc/wifi/hostapd.conf \
 $(LOCAL_PATH)/proprietary/system/etc/wifi/p2p_supplicant.conf:system/etc/wifi/p2p_supplicant.conf \
 $(LOCAL_PATH)/proprietary/system/etc/wifi/widi_supplicant.conf:system/etc/wifi/widi_supplicant.conf \
 $(LOCAL_PATH)/proprietary/system/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/00imx135.cpf:system/etc/atomisp/00imx135.cpf \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/00imx175.cpf:system/etc/atomisp/00imx175.cpf \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/00mt9e013.cpf:system/etc/atomisp/00mt9e013.cpf \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/00ov8830.cpf:system/etc/atomisp/00ov8830.cpf \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/CGamma_DIS5MP.bin:system/etc/atomisp/CGamma_DIS5MP.bin \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Mor_14MP_8BQ.txt:system/etc/atomisp/Mor_14MP_8BQ.txt \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Mor_8MP_8BQ.txt:system/etc/atomisp/Mor_8MP_8BQ.txt \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/noise.fpn:system/etc/atomisp/noise.fpn \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Preview_UserParameter_AbicoFI86A086.prm:system/etc/atomisp/Preview_UserParameter_AbicoFI86A086.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Preview_UserParameter_DIS14M.prm:system/etc/atomisp/Preview_UserParameter_DIS14M.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Preview_UserParameter_LiteOn8M.prm:system/etc/atomisp/Preview_UserParameter_LiteOn8M.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Preview_UserParameter_SemcoLc898211.prm:system/etc/atomisp/Preview_UserParameter_SemcoLc898211.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Primary_UserParameter_AbicoFI86A086.prm:system/etc/atomisp/Primary_UserParameter_AbicoFI86A086.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Primary_UserParameter_DIS14M.prm:system/etc/atomisp/Primary_UserParameter_DIS14M.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Primary_UserParameter_LiteOn8M.prm:system/etc/atomisp/Primary_UserParameter_LiteOn8M.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Primary_UserParameter_SemcoLc898211.prm:system/etc/atomisp/Primary_UserParameter_SemcoLc898211.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Video_UserParameter_AbicoFI86A086.prm:system/etc/atomisp/Video_UserParameter_AbicoFI86A086.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Video_UserParameter_DIS14M.prm:system/etc/atomisp/Video_UserParameter_DIS14M.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Video_UserParameter_LiteOn8M.prm:system/etc/atomisp/Video_UserParameter_LiteOn8M.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/Video_UserParameter_SemcoLc898211.prm:system/etc/atomisp/Video_UserParameter_SemcoLc898211.prm \
 $(LOCAL_PATH)/proprietary/system/etc/atomisp/YGamma_DIS5MP.bin:system/etc/atomisp/YGamma_DIS5MP.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/aac_dec_1.bin:system/etc/firmware/aac_dec_1.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/fa_extension.bin:system/etc/firmware/fa_extension.bin \
$(LOCAL_PATH)/proprietary/system/etc/firmware/fw_sst_08e7.bin:system/etc/firmware/fw_sst_08e7.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/isp_acc_deghosting_css15.bin:system/etc/firmware/isp_acc_deghosting_css15.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/isp_acc_fusion_css15.bin:system/etc/firmware/isp_acc_fusion_css15.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/isp_acc_multires_css15.bin:system/etc/firmware/isp_acc_multires_css15.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/isp_acc_postproc_css15.bin:system/etc/firmware/isp_acc_postproc_css15.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/isp_acc_warping_css15.bin:system/etc/firmware/isp_acc_warping_css15.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/isp_fr.bin:system/etc/firmware/isp_fr.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/mp3_dec_1.bin:system/etc/firmware/mp3_dec_1.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/msvdx_fw_mfld_DE2.0.bin:system/etc/firmware/msvdx_fw_mfld_DE2.0.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/s3202_gff.img:system/etc/firmware/s3202_gff.img \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/s3202_ogs.img:system/etc/firmware/s3202_ogs.img \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/shisp_css15.bin:system/etc/firmware/shisp_css15.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/topazsc_fw.bin:system/etc/firmware/topazsc_fw.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/vpimg_es305b.bin:system/etc/firmware/vpimg_es305b.bin \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/modem/modem_nvm.zip:system/etc/firmware/modem/modem_nvm.zip \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/modem/modem_version:system/etc/firmware/modem/modem_version \
 $(LOCAL_PATH)/proprietary/system/etc/firmware/modem/modem.zip:system/etc/firmware/modem/modem.zip \
 $(LOCAL_PATH)/proprietary/system/etc/permissions/com.intel.camera.extensions.xml:system/etc/permissions/com.intel.camera.extensions.xml \
 $(LOCAL_PATH)/proprietary/system/etc/permissions/com.intel.internal.telephony.MmgrClient.xml:system/etc/permissions/com.intel.internal.telephony.MmgrClient.xml \
 $(LOCAL_PATH)/proprietary/system/etc/permissions/com.intel.internal.telephony.OemTelephony.xml:system/etc/permissions/com.intel.internal.telephony.OemTelephony.xml \
 $(LOCAL_PATH)/proprietary/system/etc/permissions/com.intel.multidisplay.xml:system/etc/permissions/com.intel.multidisplay.xml \
 $(LOCAL_PATH)/proprietary/system/etc/permissions/com.intel.security.lib.sepdrmjni.xml:system/etc/permissions/com.intel.security.lib.sepdrmjni.xml \
 $(LOCAL_PATH)/proprietary/system/etc/permissions/com.intel.security.service.sepmanager.xml:system/etc/permissions/com.intel.security.service.sepmanager.xml \
 $(LOCAL_PATH)/proprietary/system/etc/rril/repository.txt:system/etc/rril/repository.txt \
 $(LOCAL_PATH)/proprietary/system/etc/telephony/mmgr.conf:system/etc/telephony/mmgr.conf \
 $(LOCAL_PATH)/proprietary/system/framework/com.android.future.usb.accessory.jar:system/framework/com.android.future.usb.accessory.jar \
 $(LOCAL_PATH)/proprietary/system/framework/com.android.location.provider.jar:system/framework/com.android.location.provider.jar \
 $(LOCAL_PATH)/proprietary/system/framework/com.intel.camera.extensions.jar:system/framework/com.intel.camera.extensions.jar \
 $(LOCAL_PATH)/proprietary/system/framework/com.intel.internal.telephony.OemTelephony.jar:system/framework/com.intel.internal.telephony.OemTelephony.jar \
 $(LOCAL_PATH)/proprietary/system/framework/com.intel.multidisplay.jar:system/framework/com.intel.multidisplay.jar \
 $(LOCAL_PATH)/proprietary/system/framework/com.intel.security.lib.sepdrmjni.jar:system/framework/com.intel.security.lib.sepdrmjni.jar \
 $(LOCAL_PATH)/proprietary/system/framework/com.intel.security.service.sepmanager.jar:system/framework/com.intel.security.service.sepmanager.jar \
 $(LOCAL_PATH)/proprietary/system/lib/libasfparser.so:system/lib/libasfparser.so \
 $(LOCAL_PATH)/proprietary/system/lib/libasound.so:system/lib/libasound.so \
 $(LOCAL_PATH)/proprietary/system/lib/libaudience-manager.so:system/lib/libaudience-manager.so \
 $(LOCAL_PATH)/proprietary/system/lib/libaudiohalutils.so:system/lib/libaudiohalutils.so \
 $(LOCAL_PATH)/proprietary/system/lib/libaudioresample.so:system/lib/libaudioresample.so \
 $(LOCAL_PATH)/proprietary/system/lib/libaudioutils.so:system/lib/libaudioutils.so \
 $(LOCAL_PATH)/proprietary/system/lib/libdrm.so:system/lib/libdrm.so \
 $(LOCAL_PATH)/proprietary/system/lib/libevent-listener.so:system/lib/libevent-listener.so \
 $(LOCAL_PATH)/proprietary/system/lib/libglib-2.0.so:system/lib/libglib-2.0.so \
 $(LOCAL_PATH)/proprietary/system/lib/libhwcwidi.so:system/lib/libhwcwidi.so \
 $(LOCAL_PATH)/proprietary/system/lib/libia_aiq_cp.so:system/lib/libia_aiq_cp.so \
 $(LOCAL_PATH)/proprietary/system/lib/libia_aiq.so:system/lib/libia_aiq.so \
 $(LOCAL_PATH)/proprietary/system/lib/libia_mkn.so:system/lib/libia_mkn.so \
 $(LOCAL_PATH)/proprietary/system/lib/libia_nvm.so:system/lib/libia_nvm.so \
 $(LOCAL_PATH)/proprietary/system/lib/libintelcamera_jni.so:system/lib/libintelcamera_jni.so \
 $(LOCAL_PATH)/proprietary/system/lib/libintelmetadatabuffer.so:system/lib/libintelmetadatabuffer.so \
 $(LOCAL_PATH)/proprietary/system/lib/libinterface-provider-lib.so:system/lib/libinterface-provider-lib.so \
 $(LOCAL_PATH)/proprietary/system/lib/libinterface-provider.so:system/lib/libinterface-provider.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmamgr-xmm.so:system/lib/libmamgr-xmm.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmfldadvci.so:system/lib/libmfldadvci.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmixvbp_h264.so:system/lib/libmixvbp_h264.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmixvbp_mpeg4.so:system/lib/libmixvbp_mpeg4.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmixvbp.so:system/lib/libmixvbp.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmixvbp_vc1.so:system/lib/libmixvbp_vc1.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmmgrcli.so:system/lib/libmmgrcli.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmultidisplayjni.so:system/lib/libmultidisplayjni.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmultidisplay.so:system/lib/libmultidisplay.so \
 $(LOCAL_PATH)/proprietary/system/lib/libOMXVideoDecoderAVCSecure.so:system/lib/libOMXVideoDecoderAVCSecure.so \
 $(LOCAL_PATH)/proprietary/system/lib/libOMXVideoDecoderAVC.so:system/lib/libOMXVideoDecoderAVC.so \
 $(LOCAL_PATH)/proprietary/system/lib/libOMXVideoDecoderH263.so:system/lib/libOMXVideoDecoderH263.so \
 $(LOCAL_PATH)/proprietary/system/lib/libOMXVideoDecoderMPEG4.so:system/lib/libOMXVideoDecoderMPEG4.so \
 $(LOCAL_PATH)/proprietary/system/lib/libOMXVideoDecoderWMV.so:system/lib/libOMXVideoDecoderWMV.so \
 $(LOCAL_PATH)/proprietary/system/lib/libOMXVideoEncoderAVC.so:system/lib/libOMXVideoEncoderAVC.so \
 $(LOCAL_PATH)/proprietary/system/lib/libOMXVideoEncoderH263.so:system/lib/libOMXVideoEncoderH263.so \
 $(LOCAL_PATH)/proprietary/system/lib/libOMXVideoEncoderMPEG4.so:system/lib/libOMXVideoEncoderMPEG4.so \
 $(LOCAL_PATH)/proprietary/system/lib/libparameter.so:system/lib/libparameter.so \
 $(LOCAL_PATH)/proprietary/system/lib/libproperty.so:system/lib/libproperty.so \
 $(LOCAL_PATH)/proprietary/system/lib/librapid-ril-core.so:system/lib/librapid-ril-core.so \
 $(LOCAL_PATH)/proprietary/system/lib/librapid-ril-util.so:system/lib/librapid-ril-util.so \
 $(LOCAL_PATH)/proprietary/system/lib/libreference-ril.so:system/lib/libreference-ril.so \
 $(LOCAL_PATH)/proprietary/system/lib/libril.so:system/lib/libril.so \
 $(LOCAL_PATH)/proprietary/system/lib/libsepdrmjni.so:system/lib/libsepdrmjni.so \
 $(LOCAL_PATH)/proprietary/system/lib/libsepdrm.so:system/lib/libsepdrm.so \
 $(LOCAL_PATH)/proprietary/system/lib/libSh3aParamsAbicoFI86A086.so:system/lib/libSh3aParamsAbicoFI86A086.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
 $(LOCAL_PATH)/proprietary/system/lib/libtbd.so:system/lib/libtbd.so \
 $(LOCAL_PATH)/proprietary/system/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
 $(LOCAL_PATH)/proprietary/system/lib/libtinycompress.so:system/lib/libtinycompress.so \
 $(LOCAL_PATH)/proprietary/system/lib/libva-android.so:system/lib/libva-android.so \
 $(LOCAL_PATH)/proprietary/system/lib/libvariablespeed.so:system/lib/libvariablespeed.so \
 $(LOCAL_PATH)/proprietary/system/lib/libva.so:system/lib/libva.so \
 $(LOCAL_PATH)/proprietary/system/lib/libva-tpi.so:system/lib/libva-tpi.so \
 $(LOCAL_PATH)/proprietary/system/lib/libva_videodecoder.so:system/lib/libva_videodecoder.so \
 $(LOCAL_PATH)/proprietary/system/lib/libva_videoencoder.so:system/lib/libva_videoencoder.so \
 $(LOCAL_PATH)/proprietary/system/lib/libwidiclient.so:system/lib/libwidiclient.so \
 $(LOCAL_PATH)/proprietary/system/lib/libwidimedia.so:system/lib/libwidimedia.so \
 $(LOCAL_PATH)/proprietary/system/lib/libwidirtsp.so:system/lib/libwidirtsp.so \
 $(LOCAL_PATH)/proprietary/system/lib/libwidiservice.so:system/lib/libwidiservice.so \
 $(LOCAL_PATH)/proprietary/system/lib/libwrs_omxil_common.so:system/lib/libwrs_omxil_common.so \
 $(LOCAL_PATH)/proprietary/system/lib/libwrs_omxil_core_pvwrapped.so:system/lib/libwrs_omxil_core_pvwrapped.so \
 $(LOCAL_PATH)/proprietary/system/lib/libwsbm.so:system/lib/libwsbm.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/audio_policy.redhookbay.so:system/lib/hw/audio_policy.redhookbay.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/audio.primary.redhookbay.so:system/lib/hw/audio.primary.redhookbay.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/audio.widi.redhookbay.so:system/lib/hw/audio.widi.redhookbay.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/camera.redhookbay.so:system/lib/hw/camera.redhookbay.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/gps.redhookbay.so:system/lib/hw/gps.redhookbay.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/hwcomposer.redhookbay.so:system/lib/hw/hwcomposer.redhookbay.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/lights.redhookbay.so:system/lib/hw/lights.redhookbay.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/sensors.redhookbay.so:system/lib/hw/sensors.redhookbay.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/vibrator.redhookbay.so:system/lib/hw/vibrator.redhookbay.so \
 $(LOCAL_PATH)/proprietary/system/lib/parameter-framework-plugins/Audio/libaudience-subsystem.so:system/lib/parameter-framework-plugins/Audio/libaudience-subsystem.so \
 $(LOCAL_PATH)/proprietary/system/lib/parameter-framework-plugins/Audio/libimc-subsystem.so:system/lib/parameter-framework-plugins/Audio/libimc-subsystem.so \
 $(LOCAL_PATH)/proprietary/system/lib/parameter-framework-plugins/Audio/liblpe-subsystem.so:system/lib/parameter-framework-plugins/Audio/liblpe-subsystem.so \
 $(LOCAL_PATH)/proprietary/system/lib/parameter-framework-plugins/Fs/libfs-subsystem.so:system/lib/parameter-framework-plugins/Fs/libfs-subsystem.so \
 $(LOCAL_PATH)/proprietary/system/lib/parameter-framework-plugins/System/libproperty-subsystem.so:system/lib/parameter-framework-plugins/System/libproperty-subsystem.so \
 $(LOCAL_PATH)/proprietary/system/lib/libpvr2d.so:system/lib/libpvr2d.so \
 $(LOCAL_PATH)/proprietary/system/lib/libsrv_um.so:system/lib/libsrv_um.so \
 $(LOCAL_PATH)/proprietary/system/lib/pvr_drv_video.so:system/lib/pvr_drv_video.so \
 $(LOCAL_PATH)/proprietary/system/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so:system/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/hw/gralloc.redhookbay.so:system/vendor/lib/hw/gralloc.redhookbay.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/liboclcompiler.so:system/vendor/lib/liboclcompiler.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
 $(LOCAL_PATH)/proprietary/system/usr/keylayout/cloverview_audio_Intel_MID_Audio_Jack.kl:system/usr/keylayout/cloverview_audio_Intel_MID_Audio_Jack.kl \
 $(LOCAL_PATH)/proprietary/system/usr/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
 $(LOCAL_PATH)/proprietary/system/usr/keylayout/intel_short_long_press.kl:system/usr/keylayout/intel_short_long_press.kl \
 $(LOCAL_PATH)/proprietary/system/usr/keylayout/KEYPAD.kl:system/usr/keylayout/KEYPAD.kl \
 $(LOCAL_PATH)/proprietary/system/usr/keylayout/mrst_keypad.kl:system/usr/keylayout/mrst_keypad.kl \
 $(LOCAL_PATH)/proprietary/system/usr/keylayout/mxt224_key_0.kl:system/usr/keylayout/mxt224_key_0.kl \
 $(LOCAL_PATH)/proprietary/system/usr/keylayout/rmi4_key_gff.kl:system/usr/keylayout/rmi4_key_gff.kl \
 $(LOCAL_PATH)/proprietary/system/usr/keylayout/rmi4_key.kl:system/usr/keylayout/rmi4_key.kl \
 $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_05ac_Product_0239.kl:system/usr/keylayout/Vendor_05ac_Product_0239.kl \
 $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_22b8_Product_093d.kl:system/usr/keylayout/Vendor_22b8_Product_093d.kl \
 $(LOCAL_PATH)/proprietary/system/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
 $(LOCAL_PATH)/proprietary/system/usr/share/bmd/RFFspeed_501.bmd:system/usr/share/bmd/RFFspeed_501.bmd \
 $(LOCAL_PATH)/proprietary/system/usr/share/bmd/RFFstd_501.bmd:system/usr/share/bmd/RFFstd_501.bmd \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so
